# Generated by Django 5.2.6 on 2026-10-05 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('ocr_language', models.CharField(blank=True, max_length=20)),
                ('page_summary', models.JSONField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'balance_document',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='balance_doc_status_968dd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='BalanceEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('row_index', models.IntegerField()),
                ('form_code', models.CharField(max_length=30)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('generic_name', models.TextField(blank=True)),
                ('trade_name', models.TextField(blank=True)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.TextField(blank=True)),
                ('received_from', models.TextField(blank=True)),
                ('issued_to', models.TextField(blank=True)),
                ('recipient_id', models.CharField(blank=True, max_length=100)),
                ('prescription_no', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('balance_brought', models.IntegerField(blank=True, null=True)),
                ('received', models.IntegerField(blank=True, null=True)),
                ('issued', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('review_notes', models.JSONField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='balance.balancedocument')),
            ],
            options={
                'db_table': 'balance_entry',
                'ordering': ['page_number', 'row_index'],
                'indexes': [models.Index(fields=['document', 'page_number'], name='balance_ent_documen_53661d_idx'), models.Index(fields=['document', 'needs_review'], name='balance_ent_documen_45e846_idx'), models.Index(fields=['entry_date'], name='balance_ent_entry_d_ac49a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'page_number', 'row_index'), name='uq_balance_entry_doc_page_row')],
            },
        ),
    ]
