# Generated by Django 5.2.6 on 2026-10-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceentry',
            name='entry_date_text',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
